Module8 task1
htmlacademy-react/1578123-six-cities-11 pull request #13
Opened 2022-12-12 01:33 UTC by vakhania-av

2022-12-12 13:12 UTC, Dima-Dim requested changes

2022-12-12 13:12 UTC, Dima-Dim commented on project/src/store/offers/offers.ts
> +            offer.isFavorite = action.payload.isFavorite;
Не очень хорошо так делать. Есть `offers` у которых есть id и есть `favorites` - список id. Когда нужно, происходит проверка на то есть ли данный id в `favorites`.

2022-12-12 20:50 UTC, vakhania-av commented on project/src/store/offers/offers.ts
> +            offer.isFavorite = action.payload.isFavorite;
Уловил идею, у меня структура по-другому разделена была. Можно я перед защитой поправлю, если останется время? Хочу успеть тесты написать за завтрашний день. А позже в store/offers вынесу favorites: [] и сравню по айдишникам, как рекомендовано выше. Хочу также nearby тоже вынести отдельно + селекторы

2022-12-13 07:09 UTC, Dima-Dim commented on project/src/store/offers/offers.ts
> +            offer.isFavorite = action.payload.isFavorite;
Хорошо.

2022-12-13 07:09 UTC, merged